version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
    steps:
      - checkout
     
     ## - run:
       ##   name: "Install project dependencies"
         # command: nuget restore
      - run:
          name: "Install project dependencies"
          command: MSBuild.exe HelloWorld.sln /t:Rebuild /p:DeployOnBuild=true /p:Configuration=Release  /p:SkipPostSharp=true          
      - persist_to_workspace:
          root: C:/Users/circleci/project/obj/Release
          paths:
            - Package
           
  deploy:
    docker:
    - image: circleci/python:3.6.4
    description: Build application with Release configuration
    steps:     
      - attach_workspace:
          at: ~/repo

      - run:
          name: Installing deployment dependencies
          working_directory: ~/repo/Package
          command: |
            unzip HelloWorld.zip -d Artifact
      - run:
          name: Installing deployment dependencies
          working_directory: ~/repo/Package
          command: |
            ls -a

      - run:
          name: LIst in PAckage Temp 
          working_directory: ~/repo/Package/Artifact
          command: |
            ls -a
      - run:
          name: Installing deployment dependencies
          working_directory: ~/repo
          command: |
           # sudo pip install --upgrade pip
            sudo pip install awsebcli --upgrade
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/repo/PackageTmp/.aws
            touch ~/repo/PackageTmp/.aws/config
            chmod 600 ~/repo/PackageTmp/.aws/config
            echo "[profile kenani]" > ~/repo/PackageTmp/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/repo/PackageTmp/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/repo/PackageTmp/.aws/config
      - run:
          name: Deploy to EB if branch is Master
          working_directory: ~/repo/PackageTmp
          command: |
            #eb init --region us-east-1 --platform iis-10.0 circleci-beanstalkdev
           # eb create circleci-beanstalkdev-test
workflows:
  test_and_build:
    jobs:
      - test
      - deploy:
          requires:
            - test
      

                     
