version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  publish:
    description: Build and publish 
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: Build Project 
          command: MSBuild.exe HelloWorld.sln /t:Rebuild /p:DeployOnBuild=true /p:Configuration=Release  /p:SkipPostSharp=true          
      - persist_to_workspace:
          root: C:/Users/circleci/project/obj/Release
          paths:
            - Package  
  deploy:
    docker:
    - image: circleci/python:3.6.4
    description: Deploy
    steps:     
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish Data
          working_directory: ~/repo/Package
          command: |
            unzip HelloWorld.zip -d Artifact
      - run:
          name: Installing deployment dependencies
          working_directory: ~/repo/Package/Artifact
          command: |
           # sudo pip install --upgrade pip
            sudo pip install awsebcli --upgrade
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/repo/Package/Artifact/.aws
            touch ~/repo/Package/Artifact/.aws/config
            chmod 600  ~/repo/Package/Artifact/.aws/config
            echo "[profile kenani]" > ~/repo/Package/Artifact/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/repo/Package/Artifact/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/repo/Package/Artifact/.aws/config
      - run:
          name: Deploy to EB if branch is Master
          working_directory: ~/repo/Package/Artifact
          command: |
            eb init --region us-east-1 --platform iis-10.0 circleci-beanstalk
            #eb create circleci-beanstalk-test
            eb create --keyname k8s circleci-beanstalk-devopsdev
            
workflows:
  Publish_and_build:
    jobs:
      - publish
      - deploy:
          requires:
            - publish
          filters:
            branches:
              only:
                - master

                     
