version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  check:
    docker:
    - image: circleci/python:3.6.4
    description: check pipeline
    steps:    
      - checkout
      - run:
          set -o nounset
#$IFS=$'\n' read -d '' -r -a lines < values.txt
#status=${lines[0]}
#currentpipe=${lines[1]}
echo $status
echo $currentpipe

if [ -z $status ] & [ -z $currentpipe ]
then
    echo "NULL!! "
    echo "Has dependency!!  Triggering.... pipe1"

    echo "Cancel current pipeline"
	
    exit 1

else
    echo "Has value...! "
    if [ $status = 'BLOCKED' ] && [ $currentpipe = 'pipe2' ]
    then
            echo "FOUND no dependency!! executing current Pipeline..."


    else
            echo "Has dependency!!  Triggering.... pipe1"

            echo "Cancel current pipeline"
				
	   exit 1
    fi

fi
            
      - run:
          name: env Data
          command: |
            touch ./values.txt
            chmod 777 ./values.txt
            echo "$status" >> ./values.txt
            echo "$currentpipe" >> ./values.txt
            cat ./values.txt
            chmod 777 ./check.sh
      - run:
          name: env Data
          command: |
            ls
            sh ./check.sh

  publish:
    description: Build and publish 
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: Build Project 
          command: MSBuild.exe HelloWorld.sln /t:Rebuild /p:DeployOnBuild=true /p:Configuration=Release  /p:SkipPostSharp=true   
      - persist_to_workspace:
          root: C:/Users/circleci/project/obj/Release
          paths:
            - Package  
  deploy:
    docker:
    - image: circleci/python:3.6.4
    description: Deploy
    steps:     
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish Data
          working_directory: ~/repo/Package
          command: |
            unzip HelloWorld.zip -d Artifact
            echo $status
            echo $abc
            echo ${abc}
            echo $status ${abc} << pipeline.number >>  
      - run:
          name: Cancel build
          working_directory: ~/repo/Package
          command: |
            echo $CIRCLE_BUILD_NUM
            #curl -X POST https://circleci.com/api/v1.1/project/github/ktadepalli/AspSample-1/$CIRCLE_BUILD_NUM/cancel -H "Circle-Token: 22df877158909c8e95b5f5e41e712a0a346d7ca2"  
            #curl -X POST https://circleci.com/api/v2/project/github/ktadepalli/AspSample-1/job/$CIRCLE_BUILD_NUM/cancel -H 'Accept: application/json' -H 'Circle-Token: 22df877158909c8e95b5f5e41e712a0a346d7ca2'
      - run:
          name: Installing deployment dependencies
          working_directory: ~/repo/Package/Artifact
          command: |
           # sudo pip install --upgrade pip
            sudo pip install awsebcli --upgrade
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/repo/Package/Artifact/.aws
            touch ~/repo/Package/Artifact/.aws/config
            chmod 600  ~/repo/Package/Artifact/.aws/config
            echo "[profile kenani]" > ~/repo/Package/Artifact/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/repo/Package/Artifact/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/repo/Package/Artifact/.aws/config
      - run:
          name: Deploy to EB if branch is Master
          working_directory: ~/repo/Package/Artifact
          command: |
            eb init --region us-east-1 --platform iis-10.0 circleci-beanstalk
            #eb create circleci-beanstalk-test
            eb deploy circleci-beanstalk-devopsdev
            
workflows:
  Publish_and_build:
    jobs:
      - check:
          context: Test_context
      - publish:
          context: Test_context
          requires:
            - check
      - deploy:
          context: Test_context
          requires:
            - publish
          filters:
            branches:
              only:
                - master

                     
